---
# tasks file for sslscan - Debian

- name: "Installing {{ sslscan_app }} on Debian based systems."
  apt:
    name: "{{ sslscan_app }}"
    state: "{{ sslscan_desired_state }}"
    force_apt_get: yes
    update_cache: yes
