---
# tasks file for sslscan - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ sslscan_app }}
  ansible.builtin.apt:
    name: "{{ sslscan_app }}"
    state: "{{ sslscan_desired_state }}"
    force_apt_get: yes
    update_cache: yes
